### ISSUE TITLE
NetworkImage Error

### ISSUE THREAD

**Issue by code-simple** [RipplesCode/fetch_api_data_getx#1]
I tested this source code, everything works fine but 
Images are not generating because one of the image (https://www.purpicks.com/wp-content/uploads/csm/pressed_eyeshadow_LORES_1024x1024_55deb6c3-b7cd-4cb5-9ede-f2931c07312a1.jpg)
 has timeout error , I would suggest to use any other API.
 
 Thank You

**Comment by RipplesCode** [comment]
You can try with other API
